
input_fordel_path: '/DC12/demo_data/eval/videos/DJI_0601_video3/frames/'
n_window: 24
save_folder: './demo_data/demo2/'
save_video_dir: './demo_data/demo_test.mp4'
save_window_path: './demo_data/window/'
model_detection: yolo11n-seg.pt
length_run: 0
point_not_inmask: 200
ecl_dis_match: 10
thesshold_area_each_animal: 100
save_mot: '/DC12/demo_data/'
