#input_fordel_path: '/mnt/WildLive/DJI_0601_video2/frames/'
#input_fordel_path: '/DC12/data/DJI_0117_video3_sample/frames/'
input_fordel_path: '/DC12/demo_data/jenna_vid/DJI_vid2/frames/'
n_window: 1
save_mot: './demo_data/'
save_folder: './demo_data/demo/'
save_video_dir: './demo_data/demo_test.mp4'
save_window_path: './demo_data/window/'
model_detection: 'yolov8x-seg.pt'
length_run: 300
point_not_inmask: 200
ecl_dis_match: 10
thesshold_area_each_animal: 100
windowsize: 640
#input_fordel_path: '/data/captest/cap_eval_data/vlc-record-2025-01-03-14h37m50s-DJI_20240624153820_0001_V/frames'
