<<<<<<< HEAD
input_fordel_path: '/DC12/demo_data/DJI_0117_video3/frames/'
=======
input_fordel_path: '/DC12/demo_data/eval/videos/DJI_0117_video3/frames/'
>>>>>>> 95cbc13122cbd5d42b46bd9f5c150bfe9cbeb9fd
#input_fordel_path: '/data/kenya/data_filter/video14/frames/'
n_window: 1
save_mot: './demo_data/'
save_folder: './demo_data/demo2/'
save_video_dir: './demo_data/demo_test.mp4'
save_window_path: './demo_data/window/'
model_detection: 'yolov8x-seg.pt'
length_run: 20
point_not_inmask: 200
ecl_dis_match: 10
thesshold_area_each_animal: 100

#input_fordel_path: '/data/captest/cap_eval_data/vlc-record-2025-01-03-14h37m50s-DJI_20240624153820_0001_V/frames'
