input_fordel_path: '/data/captest/cap_eval_data/uav0000009_03358_v/'
save_folder: './demo_data/demo2/'
save_video_dir: './demo_data/demo_test.mp4'
save_window_path: './demo_data/window/'
model_detection: 'yolov8x-seg.pt'
length_run: 218
point_not_inmask: 200
ecl_dis_match: 10
thesshold_area_each_animal: 1000

